version: '4'
services:
  gps-ntp:
    container_name: gps-ntp
    image: dduncandocker/gps-ntp
    cap_add:
      - SYS_TIME
    build: .
    ports:
      - "123:123/udp"
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
      - DEVICE=/dev/ttyACM0
      - TZ=America/Denver
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    privileged: true
    restart: unless-stopped
